# Generated by Django 6.0.3 on 2026-03-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_grade',
            field=models.CharField(choices=[('3', '3º ano'), ('4', '4º ano'), ('5', '5º ano'), ('6', '6º ano')], max_length=2),
        ),
    ]
