# Generated by Django 6.0.3 on 2026-04-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_profile_photo_alter_student_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='animation_level',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='break_interval_minutes',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='student',
            name='break_suggestions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sound_level',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], default='medio', max_length=10),
        ),
    ]
