# Generated by Django 6.0.3 on 2026-03-25 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('nivel-1', 'Nível 1'), ('nivel-2', 'Nível 2'), ('nivel-3', 'Nível 3'), ('nivel-4', 'Nível 4')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('difficulty_order', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='activities.content')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='activities.level')),
            ],
            options={
                'ordering': ['phase_number'],
                'unique_together': {('content', 'level', 'phase_number')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('correct_answer', models.CharField(max_length=100)),
                ('tip', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='activities.phase')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
