# Generated by Django 6.0.3 on 2026-03-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
