# Generated by Django 6.0.3 on 2026-03-27 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_questionattempt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
    ]
