# Generated by Django 6.0.3 on 2026-03-29 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_delete_questionattempt'),
        ('progress', '0001_initial'),
        ('students', '0002_alter_student_school_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPhaseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='activities.phase')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_sessions', to='students.student')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='progress.studentphasesession'),
        ),
    ]
