# Generated by Django 6.0.3 on 2026-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_studentphasesession_studentanswer_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentphasesession',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
