# Generated by Django 6.0.3 on 2026-04-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_studentphasesession_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentphasesession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentphasesession',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
